# Generated by Django 3.2.16 on 2022-11-05 15:09

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('RSVP', models.BooleanField(default=False)),
                ('RSVP_comment', models.CharField(max_length=200)),
                ('hotel', models.CharField(max_length=200)),
                ('party_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invite.guests')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('website', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wedding_date', models.DateField()),
                ('venue1', models.CharField(max_length=100)),
                ('venue1_time', models.TimeField()),
                ('venue1_address', models.TextField()),
                ('venue2', models.CharField(max_length=100)),
                ('venue2_time', models.TimeField()),
                ('venue2_address', models.TextField()),
                ('menu', cloudinary.models.CloudinaryField(max_length=255)),
                ('starter1', models.CharField(max_length=200)),
                ('starter2', models.CharField(max_length=200)),
                ('starter3', models.CharField(max_length=200)),
                ('main1', models.CharField(max_length=200)),
                ('main2', models.CharField(max_length=200)),
                ('main3', models.CharField(max_length=200)),
                ('dessert1', models.CharField(max_length=200)),
                ('dessert2', models.CharField(max_length=200)),
                ('dessert3', models.CharField(max_length=200)),
                ('other_info', models.TextField(max_length=200)),
                ('starter1_ingredients', models.TextField()),
                ('to_be_wed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invite.guests')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invite.guests')),
            ],
            options={
                'ordering': ['-song'],
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_sent', models.DateField(auto_now=True)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invite.guests')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now=True)),
                ('order', models.IntegerField(unique=True)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invite.guests')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starter', models.CharField(choices=[], default=None, max_length=200)),
                ('main', models.CharField(choices=[], default=None, max_length=200)),
                ('dessert', models.CharField(choices=[], default=None, max_length=200)),
                ('allergies', models.CharField(max_length=100)),
                ('diet', models.CharField(max_length=100)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invite.guests')),
            ],
        ),
    ]
