# Generated by Django 3.2.16 on 2022-11-05 15:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guests',
            new_name='Guest',
        ),
        migrations.RenameModel(
            old_name='Hotels',
            new_name='Hotel',
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
