# Generated by Django 3.2.16 on 2022-11-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0002_auto_20221105_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='to_be_wed',
        ),
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(default='placeholder', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
