# Generated by Django 3.2.16 on 2022-11-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0004_auto_20221107_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='linked_party',
            field=models.ManyToManyField(blank=True, related_name='_invite_guest_linked_party_+', to='invite.Guest'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='party_admin',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
