# Generated by Django 3.2.16 on 2022-11-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0005_auto_20221107_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='linked_party',
            field=models.ManyToManyField(default=None, related_name='_invite_guest_linked_party_+', to='invite.Guest'),
        ),
    ]
