# Generated by Django 3.2.16 on 2022-11-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0013_wedding_rsvp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedding',
            name='venue1_lat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='venue1_lon',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='venue2_lat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='wedding',
            name='venue2_lon',
            field=models.TextField(blank=True),
        ),
    ]
