# Generated by Django 3.2.16 on 2022-11-25 17:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0015_auto_20221125_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='menu',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
