# Generated by Django 3.2.16 on 2022-12-01 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0017_alter_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='dessert',
            field=models.CharField(choices=[('dessert1', 'Sticky toffee pudding'), ('dessert2', 'Trio of ice cream'), ('dessert3', 'Cheese Board')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='guest_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invite.guest'),
        ),
        migrations.AlterField(
            model_name='food',
            name='main',
            field=models.CharField(choices=[('main1', 'Butternut squash ravioli'), ('main2', 'Monkfish, butterhead lettuce and dill'), ('main3', 'Braised pork with potatos and carrots')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='starter',
            field=models.CharField(choices=[('starter1', 'Tomato and basil Soup'), ('starter2', 'White crab meat tart, dressed with coastal herbs'), ('starter3', 'Duck pate')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
